# Use a base Python image
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt  --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org

# Copy the rest of your project files into the container
COPY . .

# Expose port 5000 for Flask
EXPOSE 5000

# Start the Flask application
CMD python app.py