site_name: Cyberbro Documentation
site_url: https://docs.cyberbro.net
repo_url: https://github.com/stanfrbd/cyberbro
repo_name: stanfrbd/cyberbro
edit_uri: edit/main/docs/
theme:
  name: material
  logo: images/cyberbro.svg
  favicon: images/favicon.png
  font:
    text: 'Segoe UI, Helvetica, Arial, sans-serif'
    code: 'Fira Mono, Menlo, Consolas, Monaco, monospace'
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start & Installation: quick-start/Quick-start-&-Installation.md
      - Reload Secrets & Configuration: quick-start/Reload-secrets-and-configuration.md
      - API Usage & Engine Names: quick-start/API-usage-and-engine-names.md
      - Advanced Options for Deployment: quick-start/Advanced-options-for-deployment.md
      - Upgrade Cyberbro: quick-start/Upgrade-Cyberbro.md
  - Integrations:
      - Cyberbro in KASM Workspaces: integrations/Cyberbro-in-KASM-Workspaces.md
      - Cyberbro Browser Extension: integrations/Cyberbro-browser-extension.md
      - Use Cyberbro MCP for LLM: integrations/Use-Cyberbro-MCP-for-LLM.md
      - Reverse Proxy Configuration (Caddy): integrations/Reverse-Proxy-configuration-‐-Caddy.md
  - API Keys:
      - Get AbuseIPDB API Key: api-keys/Get-AbuseIPDB-API-key.md
      - Get AlienVault API Key: api-keys/Get-AlienVault-API-key.md
      - Get Crowdstrike API Credentials: api-keys/Get-Crowdstrike-API-Credentials.md
      - Get Google Safe Browsing API Key: api-keys/Get-Google-Safe-Browing-API-key.md
      - Get IPinfo API Key: api-keys/Get-IPinfo-API-key.md
      - Get MDE (Microsoft Defender for Endpoint) API Credentials: api-keys/Get-MDE-(Microsoft-Defender-for-Endpoint)-API-credentials.md
      - Get MISP API Key: api-keys/Get-MISP-API-key.md
      - Get OpenCTI API Key: api-keys/Get-OpenCTI-API-key.md
      - Get Shodan API Key: api-keys/Get-Shodan-API-key.md
      - Get VirusTotal API Key: api-keys/Get-VirusTotal-API-key.md
      - Get WebScout API Key: api-keys/Get-WebScout-API-key.md
  - Development & Contributing:
      - Documentation: contribute/Documentation.md
      - Coding Style: contribute/Coding-Style.md
      - Contributions: contribute/Contributions.md
  - Troubleshooting:
      - Common Issues: troubleshooting/Common-Issues.md
  - Community:
      - They talk about Cyberbro: community/They-talk-about-Cyberbro.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stanfrbd/cyberbro
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/cyberbro_cti
    - icon: fontawesome/brands/mastodon
      link: https://infosec.exchange/@cyberbro
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors:
      show_email_address: false
      enabled_on_serve: false
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
copyright: Copyright © 2024 - 2025 Stanislas MEDRANO (stanfrbd) - MIT License