from typing import Annotated, Self

from pydantic import BaseModel, Field, model_validator

from models.report import BaseReport

"""
Initially generated by datamodel-codegen:
timestamp: 2025-07-06T22:18:46+00:00

Generated by command:
# datamodel-codegen --input vault.json --input-file-type json --output \
  response_modelv3.py --output-model-type pydantic_v2.BaseModel \
  --use-generic-container-types  --use-standard-collections --use-annotated \
  --use-union-operator  --reuse-model --use-double-quotes --force-optional

We've since added the default_*_factory functions and other features
for usability and reliability enhancements
"""


def default_related_factory():
    # instance: Related = Related()
    return Related()


def default_alienvault_factory():
    # instance: Alienvault = Alienvault()
    return Alienvault()


def default_pulse_info_factory():
    # instance: PulseInfo = PulseInfo()
    return PulseInfo()


def default_other_factory():
    # instance: Other = Other()
    return Other()


class MalwareFamily(BaseModel):
    id: str = ""
    display_name: str = ""


class Pulse(BaseModel, extra="ignore"):
    id: str | None = None
    name: str = "Unknown"
    description: str = ""
    created: str = ""
    references: Annotated[list[str], Field(default_factory=list)]
    adversary: str = ""
    malware_families: Annotated[list[MalwareFamily], Field(default_factory=list)]


class Alienvault(BaseModel, extra="ignore"):
    adversary: Annotated[list[str], Field(default_factory=list)]
    malware_families: Annotated[list[str], Field(default_factory=list)]


class Other(BaseModel, extra="ignore"):
    adversary: Annotated[list[str], Field(default_factory=list)]
    malware_families: Annotated[list[str], Field(default_factory=list)]


class Related(BaseModel, extra="ignore"):
    alienvault: Annotated[Alienvault, Field(default_factory=default_alienvault_factory)]
    other: Annotated[Other, Field(default_factory=default_other_factory)]


class PulseInfo(BaseModel, extra="ignore"):
    count: int = 0
    pulses: Annotated[list[Pulse], Field(default_factory=list)]
    references: Annotated[list[str], Field(default_factory=list)]
    related: Annotated[Related, Field(default_factory=default_related_factory)]

    @model_validator(mode="after")
    def _model_validator(self) -> Self:
        self.count = len(self.pulses)
        return self


class OTXReport(BaseModel, extra="ignore"):
    indicator: str
    pulse_info: Annotated[PulseInfo, Field(default_factory=default_pulse_info_factory)]


class PulseData(BaseModel):
    title: str = ""
    url: str = ""
    malware_families: Annotated[set[str], Field(default_factory=set)]
    adversary: Annotated[list[str], Field(default_factory=list)]

    def __hash__(self):
        return hash((self.title, self.url))

    def __eq__(self, other):
        if not isinstance(other, PulseData):
            return NotImplemented
        return self.title == other.title and self.url == other.url


class AlienvaultReport(BaseReport):
    count: int = 0
    pulse_data: Annotated[set[PulseData], Field(default_factory=set)]
    malware_families: Annotated[set[str], Field(default_factory=set)]
    adversary: Annotated[set[str], Field(default_factory=set)]
    link: str = ""
